test_data = [
    {
        'data':
        [
            ['Who was Jim Henson? Jim [MASK] was a puppeteer.',
             None,
             'henson',
             0.55],
            ['The first Star wars movie came out in [MASK].',
             None,
             '1977',
             0.55],
            ['We should go to [MASK] mall.',
             None,
             'the',
             0.55],
            ['A Toyota Camry is a [MASK], not a truck.',
             None,
             'car',
             0.55],
            ['I love apples. There are a lot of fruits in the world that I '
             '[MASK], but apples would be my favorite fruit',
             None,
             'love',
             0.55],
            ['That is a squirrel. A squirrel is [MASK] a dog.',
             None,
             'not',
             0.55],
            ['John is not smart. [MASK] is an idiot.',
             None,
             'john',
             0.55],
            ['Bert and Ernie lived together on Sesame street. Bert [MASK] '
             'Ernie were roomates.',
             None,
             'and',
             0.55],
            ['Winter is very cold in Canada. [MASK] is a cold season.',
             None,
             'cold',
             0.55],
            ['Santa Claus delivers gifts on Christmas. [MASK] Claus makes '
             'children happy when he gives them presents.',
             None,
             'Santa',
             0.55]
        ],
        'id': 'without options'
    },
    {
        'data':
        [
            ['Who was Jim Henson? Jim [MASK] was a puppeteer.',
             ['henson', 'he', 'cat', 'red', 'smith'],
             'henson',
             0.55],
            ['The first Star wars movie came out in [MASK].',
             ['dog', 'car', '1977', '1804', '2000', 'bread'],
             '1977',
             0.55],
            ['We should go to [MASK] mall.',
             ['penguin', 'blue', 'the', 'and', 'true'],
             'the',
             0.55],
            ['A Toyota Camry is a [MASK], not a truck.',
             ['dog', 'john', 'white', 'car', 'van', 'truck'],
             'car',
             0.55],
            ['I love apples. There are a lot of fruits in the world that I '
             '[MASK], but apples would be my favorite fruit',
             ['like', 'love', 'bread', 'john', 'hate'],
             'love',
             0.55],
            ['That is a squirrel. A squirrel is [MASK] a dog.',
             ['and', 'cat', 'not', 'also', 'claw'],
             'not',
             0.55],
            ['John is not smart. [MASK] is an idiot.',
             ['bread', 'kevin', 'smith', 'cat', 'hello'],
             'john',
             0.55],
            ['Bert and Ernie lived together on Sesame street. Bert [MASK] '
             'Ernie were roomates.',
             ['the', 'car', 'also', 'and', 'john', 'fly'],
             'and',
             0.55],
            ['Winter is very cold in Canada. [MASK] is a cold season.',
             ['hot', 'winter', 'summer', 'john', 'kangaroo', 'blue'],
             'winter',
             0.55],
            ['Santa Claus delivers gifts on Christmas. [MASK] Claus makes '
             'children happy when he gives them presents.',
             ['why', 'and', 'santa', 'john', 'smith', 'fries'],
             'santa',
             0.55]
        ],
        'id': 'with options"'
    },
]
